### ISSUE TITLE
Visualize annotation progress on current image set on home page

### ISSUE THREAD

**Issue by boazsender** [bocoup/image-annotator#118]
Goal, showing people what they are contributing to; what needs to be done, what you can do?
- [x] expose ReST API for current image set and current know images
- [x] implement progress bar on home page

Progress will be calculated based on the number of images annotated at least once divided by total number of images.

see issue #25 for the beginning of this conversation.

CC @tafsiri @pbeshai @vlandham @iros

**Comment by boazsender** [comment]
@joyab the progress bar landed in master this morning (via #145 and #158), and is up on staging (http://ajl-staging.bocoup.org) right now. What do you think?

Also, CC @tafsiri, @vlandham, @pbeshai  and @iros, we've got an issue here where when the system launches, there will be 20k images, and it will take a while before the progress bar shows meaningful movement.

Do you have any ideas about how to make this progress metric more engaging at the beginning of the annotation campaign?

**Comment by tafsiri** [comment]
@boazsender i'd suggest changing the copy up to something more call to action-y.

e.g. "We are currently missing data/labels/tags for X images out of Y images. Help us get to our goal/Help us create a benchmark with diverse faces"

**Comment by tafsiri** [comment]
You could also show a few examples of things that need to be tagged (a little thumbnail gallery of faces)

**Comment by vlandham** [comment]
yeah that was what hit me initially. if the goal is to get folks engaged, then at the least a "We have X% of X images tagged, help us improve!" line below the chart would be useful. 

To better clarify the content of the barchart you could invent a "Project Status" scale, so like before the barchart, have a big :

Project Status: infancy (we are just starting this initiative. With your help we will get this project to mature soon)

project statuses could be age based:
* infancy
* adolescent
* mature

or just:
* start
* middle
* end

**Comment by iros** [comment]
@boazsender - how many taggings of a face are you collecting? I believe m-turk papers have suggested 7 to get to agreement.

**Comment by boazsender** [comment]
@tafsiri and @vlandham good call, I'm going with 

```We have X% of X images annotated, help us get to our goal so that we can create a face recognition benchmark with diverse faces!```

I'm also going to move to try moving it to the top @isaacdurazo. PR incoming

What do you think? CC @joyab

**Comment by boazsender** [comment]
These changes have been made and are up on https://ajl-staging.bocoup.org. What do you think @tafsiri @vlandham @iros @joyab ?

**Comment by joyab** [comment]
ACTIVITY METRIC
Since each image needs 3 tags, reporting the number of tags submitted can give a bigger picture of how much activity is going.

[PROGRESS BAR] 

Phase 1: Faces tagged <= 5%
X tags have been submitted 

Phase 2:  Faces tagged > 5%
X tags have been submitted  on Y% of images      

In issue #121, I have draft call to action text.

**Comment by boazsender** [comment]
@joyab are you suggesting that we don't show the progress bar until we are at 5% of our goal?

**Comment by boazsender** [comment]
I'm going to mark this complete for 0.1. Happy to open a new issue for 0.2, or keep the conversation going in #25.
