### ISSUE TITLE
Setup launch workload

### ISSUE THREAD

**Issue by boazsender** [bocoup/image-annotator#119]
We have ~500k images from imdb-wiki set of ~20k unique subjects.

we don't need all 500k to get a sense of demo of the set, we only need one of each unique subject.

Since don't have a way to prioritize specific images yet, or a concept of unique subjects, let's only load in one image for each of these ~20k unique subjects.

**Comment by boazsender** [comment]
@joyab How do we want to prioritize workloads? For example, do we want to cycle through all 20k images, or do we want to cycle through say, the firs 1k images 5 times.

**Comment by gnarf** [comment]
Or rather, how do we want to shape the data we get back.

Would we prefer trying to capture a whole lot of annotations about a very little set of images, or getting very little information about a whole lot of images?

I feel like a decent approach would be to aim for 10 "enrolled" annotators per image before moving onto a new image.  This is a pretty complex ordering scheme, but I think we could do it such that images get pulled out of the "to annotate" bucket using the following priorities

* Has more than 0 but less than 10 annotators 
* Has 0 annotators
* Has more than 10 annotators (-or- yay! we are done if we pick here!!!)

**Comment by boazsender** [comment]
I like that ordering @gnarf.

The only concern I have is cross session repetition of images to users. Would that be an issue?.. if a user closes their browser, comes back, and gets the same image again?

**Comment by gnarf** [comment]
> Would that be an issue?.. if a user closes their browser, comes back, and gets the same image again?

It would be much more likely, yes, we could use some sort of "total random pool size", draw say 5,000 images out of the buckets, in the specified order, then shake them up before selecting the 1 or 3 images for the user to annotate

**Comment by boazsender** [comment]
The plan is to take the bucketed approach with buckets of 2k. per @gnarf and @joyab

**Comment by boazsender** [comment]
- [ ] load LFW onto s3
- [ ] select one image per person from imdb
- [ ] blow out production DB and replace it with the launch worklaod
- [ ] prioritize images into buckets (2k at a time)

**Comment by gnarf** [comment]
> prioritize images into buckets (2k at a time)

I'm going to mark this done, but what I actually did was prioritize the images into A bucket that was 2k deep -- so the first 2k to "start" will fill the bucket first, and then as those complete and leak out, new ones will fill into it, when there are no more new ones, the already complete ones will begin to resurface based on the count of annotations

**Comment by gnarf** [comment]
Also, I marked this task "in review" -- the data is live, would you care to play with it?

**Comment by boazsender** [comment]
This has been completed. We have 20922 in production. Launch workload is setup.
