### ISSUE TITLE
Onboarding/Homepage Starter Text

### ISSUE THREAD

**Issue by joyab** [bocoup/image-annotator#121]
Each new session can begin with an on boarding workflow to explain what we are doing, review the tagging process, and provide a way for users to leave feedback.

**1. Make a Difference**
Algorithms are trained and tested with data sets. A lack of diversity in these data sets can lead to biased systems. Help us check for bias by tagging influential data sets.

**2. Simple Actions Matter**
The simple action of tagging face images with perceived age,  gender, and ethnicity will generate bias busting information that will inform the creation of inclusive technology.
[Include GIF of the tagging process]

****3. Be Heard**
As algorithms increasingly influence more aspects of our lives, we need ways to keep coded systems accountable.  Please be in touch with questions, comments, concerns, and experiences relating to algorithmic bias.  [Contact Button -> Lead to Form has Captach etc]

**Comment by boazsender** [comment]
@joyab a first pass at this on the home page is currently deployed to staging: https://ajl-staging.bocoup.org.

Can you take a look and make sure we're going in the right direction?

**Comment by joyab** [comment]
@boazsender  @isaacdurazo 
The home page is really starting to come together. To be in compliance with MIT research requirements we need to include a consent screen/modal before annotations begin. Details below:

**CHANGES**

**Header:**
Replace  _The Computer Vision Benchmarking Project_ w/
Destiny Unveiled: Facial Data Transparency Project

**Intro text:**
Replace _We have 38 of 4151 images annotated, help us get to our goal so that we can create a face recognition benchmark with diverse faces!_ w/

**If data is destiny, how inclusive is our future data-centric technology?** How representative are the datasets being used to train machines to analyze faces? Help us find out by tagging training images .

Progress - Volunteers have tagged X out of Y faces.

 **Call to Action Button**
 Text -Start Tagging-

It may not be intuitive for users to click annotate to get started
A fight bias button can go  immediately after the progress bar.
Once we get to the point of collecting new data where appropriate the next project can be Destiny Reclaimed.

**Comment by boazsender** [comment]
@joyab thanks for the review!

One question, are you saying the hompage CTA under the progress bar should be "start tagging" or "fight bias"?

And if it's "start tagging", should the top nave change from "annotate" to "tag"? What do you think?

**Comment by joyab** [comment]
@boazsender Let's go with Start Tagging which is more task oriented.

**Comment by boazsender** [comment]
OK, that's up in #121, I'll move to review on that and try to land it today

**Comment by boazsender** [comment]
These updates landed as part of #174 and should be live on production shortly. closing.
