### ISSUE TITLE
Implement a flagging workflows for "bad photos"

### ISSUE THREAD

**Issue by boazsender** [bocoup/image-annotator#136]
EG: not a face, more than one face, etc

remove images from rotation after the following criteria:
* remove image after 2 flags if no annotations exist.
* if annotations exist remove after more flags have been submitted than annotations.

**Comment by gnarf** [comment]
We should ask for every image, before they annotate it if the image has the attributes we want in a training image:

* Single face
* Clear front facing shot
* A human

We could actually make this an annotation type I think

Is there a better list of criteria for this?

**Comment by boazsender** [comment]
Implement the following worklow:

Add a flag button in the labeling header that toggles the annotation tile to flagging with the following options:
* unclear subject
* no subject in picture
* inappropriate content
* @joyab any others?

In flagging state, change "flag" button to close button.

**Comment by boazsender** [comment]
Progress on this happening in #169

**Comment by boazsender** [comment]
@isaacdurazo can you add a flagging button by PR to #169 and communicate where it is to @kadamwhite

**Comment by boazsender** [comment]
todo:
- [ ] add flag button
- [ ] hide demographic 3 step progress bar when clicked and show flag ui in place of demographic attributes
- [ ] stop serving images when the number of flags exceeds the number of annotations, or when there are no annotations, require 2 flags.

**Comment by boazsender** [comment]
for reference this is how it looks by default right now:
![image](https://cloud.githubusercontent.com/assets/122117/24714382/50afadd6-19f6-11e7-9175-a3a8cbf87d9b.png)

**Comment by boazsender** [comment]
@gnarf the UI from @kadamwhite and your initial backend work are landed in master. All that's left to do is checkbox #3 above: "stop serving images when the number of flags exceeds the number of annotations, or when there are no annotations, require 2 flags.".

**Comment by boazsender** [comment]
As of #188 and #189, this has been completed. Great work @gnarf!
