### ISSUE TITLE
Establish Routing

### ISSUE THREAD

**Issue by kadamwhite** [bocoup/image-annotator#15]
We should implement a front-end router for the React application, and determine what the server infrastructure will be: should this be purely static w/ front-end routing, or have a server, etc

**Comment by boazsender** [comment]
Can I tack on the navigation UI to this issue?

There should be four high level routes for public "lady justice" users:
* demographics
* regions
* landmarks
* home

You can see this here (the logo should direct the user home): https://invis.io/HKACANH6Z#/218146723_Perceived_Gender_-_Desktop
