### ISSUE TITLE
Enhance workload checkpoints

### ISSUE THREAD

**Issue by boazsender** [bocoup/image-annotator#166]
* Add feedback form CTA to 1st workload complete checkpoint
* In uppercase the font
* Experiment with color to draw attention to message

**Comment by boazsender** [comment]
I landed the following interface and flow changes in PR #168:

![progress-ajl](https://cloud.githubusercontent.com/assets/122117/24691060/480a2c62-199f-11e7-884a-c44ddd389eee.png)

![progress-ajl](https://cloud.githubusercontent.com/assets/122117/24691062/495d1c0a-199f-11e7-9f56-4511a03a7aa7.png)

Do we think this handles this correctly?

**Comment by joyab** [comment]
Looks good.

**Comment by boazsender** [comment]
Great, this has been merged. We actually made a few updates to improve contrast since this screenshot. 

Thanks for the approval. Closing.
