### ISSUE TITLE
create home page

### ISSUE THREAD

**Issue by boazsender** [bocoup/image-annotator#20]
https://invis.io/HKACANH6Z#/221452966_Welcome_-_Admin_Lady_Justice

![image](https://cloud.githubusercontent.com/assets/442115/23560434/6c5f55de-0008-11e7-85c8-63e10194f24c.png)

**Comment by boazsender** [comment]
@isaacdurazo do you think it would be possible to add an animated gif of how the system works?

**Comment by joyab** [comment]
Some visual representation of the tasks i believe will be the crowning addition.

**Comment by boazsender** [comment]
closing this in favor of #177
