### ISSUE TITLE
Add a google form to optionally capture email address of annotators

### ISSUE THREAD

**Issue by boazsender** [bocoup/image-annotator#27]

**Comment by boazsender** [comment]
@joyab we've added a [feedback from](https://docs.google.com/a/bocoup.com/forms/d/1UsW1hGalLGVQ8xSdCpDp_tq2So24tdiq084n8wUiWic/edit) to the home page under "contact us". This landed in pr #158. 

Does this work for the purposes of collecting feedback for beta launch? 

Would you like different questions? I made you collaborator, so you can log in and update them, or contemplate them here.

Also, would you like to see this form CTA show up anywhere else? I was thinking perhaps the footer, and after the first workload is complete? Or the second?

Also, instead of "contact us", I was thinking "how is this working", or "give feedback" What do you think?

**Comment by joyab** [comment]
Submit Feedback works. 
The questions look good

**Comment by boazsender** [comment]
Great, then this is complete. Closing. Thanks for the review @joyab!
