### ISSUE TITLE
Design UX checkpoint feedback system

### ISSUE THREAD

**Issue by kadamwhite** [bocoup/image-annotator#74]
Such as,

- You've finished a workload & passed validation - take a moment to call that out, then here's the next workload
- You've finished a workload and your answers do not match the "truths" - call that out and give them ability to re-start w/ the new workload
- You just tried to annotate a workload that was not sent to you
- You have been "enrolled"

Some of the errors (see #53) are more a "state" that the user is in, rather than a system error; we should expand whatever we do for error handling, to account for these workflow actions

**Comment by kadamwhite** [comment]
@boazsender can you provide a list of the UI cues you would like to see implemented as part of this issue? We should have user stories to guide this work.

**Comment by boazsender** [comment]
On pitch:
* Beginning a workload
* completing a workload and getting another one
* completing a second workload - wow, youre a champe
* completing a third workload- youre on fire
* failing a workload because you got one known truth wrong
* getting a truth right, and making a contribution

CC @joyab what do you think?

**Comment by boazsender** [comment]
see #104 for adding a "you've done it!" if the user ever annotates all the images.

**Comment by kadamwhite** [comment]
In planning, these two:

- failing a workload because you got one known truth wrong
- getting a truth right, and making a contribution

were called out as problematic because they reveal information to the annotator which could potentially be used to game the system

**Comment by joyab** [comment]
Perceived Gender and perceived Ethnicity need to be correct. Age can have
variability. The ground truth images should be as unambiguous as possible.
Borderline images should not be used as the gold standards.

**Comment by boazsender** [comment]
@joyab, can you review the workflow messages in the app? For reference, they are:

* "Welcome! This is your first batch of images.';"
* "You've completed your first batch—great!"
* after 2 batches"You're a champ!"
* after 3"You're on fire!"
* after 4+ "You've completed ${count} batches! Amazing!"

**Comment by boazsender** [comment]
closing per @joyab's +1

Joy, if you ever want to edit the text, the copy is in this file: https://github.com/bocoup/image-annotator/blob/master/frontend/services/content.js
