### ISSUE TITLE
explore loading IMDB wiki into db

### ISSUE THREAD

**Issue by boazsender** [bocoup/image-annotator#92]
https://data.vision.ee.ethz.ch/cvl/rrothe/imdb-wiki/

**Comment by boazsender** [comment]
select one image per celebrity.

**Comment by gnarf** [comment]
See also #57

**Comment by gnarf** [comment]
So I've pretty much extracted the needed data from the matlab file included with the IMDB dump:

https://github.com/bocoup/image-annotator/blob/matlab-converter/MatLab%20Converter.ipynb

https://github.com/bocoup/image-annotator/raw/matlab-converter/matlabby.csv

I have the images themselves on an s3:

https://s3.amazonaws.com/image-annotator-assets/imdb_crop/02/nm0000002_rm1075631616_1924-9-16_1991.jpg

There are however some problems where it seems the "cropping" algo accidentally crops the wrong face out of the image:

one example -- this image of marlon brando's chin:

```
124,66,"(500, 500)",1.0,Marlon Brando,08/nm0000008_rm2517339648_1924-4-3_1990.jpg
```
![test](https://s3.amazonaws.com/image-annotator-assets/imdb_crop/08/nm0000008_rm2517339648_1924-4-3_1990.jpg)

**Comment by boazsender** [comment]
@joyab's response in email:
```
Hi Corey,

These training sets often come with errata. 
One approach could be to use images that contain just one face for the MVP. The dlib face detector can be used for this purpose.
Only include image if 1 face is detected - Flag image otherwise.
Here is some dlib reference code.
https://github.com/kylemcdonald/ml-examples/blob/master/workshop/faces/Face%20Detection%2C%20Tracking%2C%20and%20Recognition.ipynb
```

**Comment by boazsender** [comment]
@gnarf's response in email:
```
even filtering for some of these "second_face_score is nan" records:

502,71,"(209, 208)",1.0,Stanley Kubrick,40/nm0000040_rm3260468224_1928-7-26_1999.jpg,True

does this look like s 71yr Stanley Kubrick to you
![unnamed](https://cloud.githubusercontent.com/assets/122117/24215585/a15cc486-0f0f-11e7-9145-85fd8b66eec6.png)
```

**Comment by boazsender** [comment]
From @joyab in response from email:
```
This definitely makes the case for getting new labels from our process on a public training set.

We can use LFW as our annotation verification photos and have IMDB-WIKI as the new photos to be labeled.

We should still record the original label, so that we can run analysis  on the original labels that conflict with the annotations we collect from the crowd.```

**Comment by boazsender** [comment]
@joyab do you/we have reliable ground truths for LFW?

**Comment by boazsender** [comment]
this has been completed, moving to #119 to do the actual import.
